# Schema for the configuration files of the event module.

event.settings:
  type: config_object
  label: 'Event settings'
  mapping:
    use_admin_theme:
      type: boolean
      label: 'Use administration theme when editing or creating content'

event.type.*:
  type: config_entity
  label: 'Content type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    preview_mode:
      type: integer
      label: 'Preview before submitting'
    display_submitted:
      type: boolean
      label: 'Display setting for author and date Submitted by post information'

# Plugin \Drupal\event\Plugin\Search\EventSearch
search.plugin.event_search:
  type: mapping
  label: 'Content search'
  mapping:
    rankings:
      type: sequence
      label: 'Content ranking'
      sequence:
        type: integer
        label: 'Influence'

action.configuration.event_assign_owner_action:
  type: mapping
  label: 'Change the author of content configuration'
  mapping:
    owner_uid:
      type: text
      label: 'Username'

action.configuration.event_unpromote_action:
  type: action_configuration_default
  label: 'Demote selected content from front page configuration'

action.configuration.event_promote_action:
  type: action_configuration_default
  label: 'Promote selected content from front page configuration'

# @deprecated in Drupal 8.5.x, to be removed before Drupal 9.0.0.
# @see https://www.drupal.org/event/2919303
action.configuration.event_publish_action:
  type: action_configuration_default
  label: 'Publish selected content configuration'

# @deprecated in Drupal 8.5.x, to be removed before Drupal 9.0.0.
# @see https://www.drupal.org/event/2919303
action.configuration.event_unpublish_action:
  type: action_configuration_default
  label: 'Unpublish selected content configuration'

# @deprecated in Drupal 8.5.x, to be removed before Drupal 9.0.0.
# @see https://www.drupal.org/event/2919303
action.configuration.event_save_action:
  type: action_configuration_default
  label: 'Save content configuration'

action.configuration.event_delete_action:
  type: action_configuration_default
  label: 'Delete content configuration'

action.configuration.event_make_sticky_action:
  type: action_configuration_default
  label: 'Make selected content sticky configuration'

action.configuration.event_make_unsticky_action:
  type: action_configuration_default
  label: 'Make selected content unsticky configuration'

action.configuration.event_unpublish_by_keyword_action:
  type: mapping
  label: 'Unpublish content containing keyword(s) configuration'
  mapping:
    keywords:
      type: sequence
      label: 'Keywords'
      sequence:
        type: string
        label: 'Keyword'

block.settings.event_syndicate_block:
  type: block_settings
  label: 'Syndicate block'
  mapping:
    block_count:
      type: integer
      label: 'Block count'

condition.plugin.event_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string
